export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';
export const GET_SEARCH_FAILURE = 'GET_SEARCH_FAILURE';
export const GET_SEARCH_START = 'GET_SEARCH_START';
export const GET_SEARCH_REQUEST = 'GET_SEARCH_REQUEST';
export const CHANGE_COLUMNS_COUNT = 'CHANGE_COLUMNS_COUNT';
